server {
    listen 8080; # Обязательно > 1024 для non-root
    server_name localhost;

    location / {
        proxy_pass http://web1:80; # Имя сервиса WordPress из compose
        proxy_set_header Host $http_host; # Передает localhost:8083, а не просто localhost
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
