stages:
  - lint
  - security
  - test
  - build
  - cleanup

variables:
  DOCKER_DRIVER: overlay2
  BOT_IMAGE: $CI_REGISTRY_IMAGE/bot:$CI_COMMIT_REF_SLUG
  WEATHER_IMAGE: $CI_REGISTRY_IMAGE/weather:$CI_COMMIT_REF_SLUG

# 1. Линтинг
lint-code:
  stage: lint
  image: python:3.10-slim
  script:
    - pip install flake8
    - flake8 Lab-4/Bot/ Lab-4/weather/ --exclude=venv,migrations --max-line-length=127

# 2. Безопасность
secret-scan:
  stage: security
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    # Флаг --no-git заставляет gitleaks смотреть только на файлы, а не в историю коммитов
    - gitleaks detect --verbose --source Lab-4/ --no-git

# 3. Тесты
run-tests:
  stage: test
  image: python:3.10-slim
  services:
    - name: hashicorp/vault:latest
      alias: vault
      command: ["server", "-dev", "-dev-root-token-id=root"]
  variables:
    VAULT_ADDR: "http://vault:8200"
  script:
    - pip install -r Lab-4/Bot/requirements.txt hvac pytest
    - python -m pytest Lab-4/Bot/

# 4. Сборка 
build-images:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $BOT_IMAGE -f Lab-4/Bot/Dockerfile Lab-4/
    - docker build -t $WEATHER_IMAGE -f Lab-4/weather/Dockerfile Lab-4/
    - docker push $BOT_IMAGE
    - docker push $WEATHER_IMAGE
  only:
    - main

# 5. Очистка
clean-up:
  stage: cleanup
  script:
    - echo "Cleaning up..."
  when: always