# bad ci/cd

image: docker:latest

services:
  - docker:dind

stages:
  - build_and_deploy

variables:
  TELEGRAM_TOKEN: "12345678:ABCDEF"
  WEATHER_API_KEY: "secret-key-123"

build_and_deploy:
  stage: build_and_deploy
  tags:
    - saas-linux-small-amd64
  script:
    - docker build -t weather-logic ./Lab-4/weather
    - docker build -t telegram-bot ./Lab-4/Bot
    - echo "Deploying . . . "
    - export TELEGRAM_TOKEN="123456789:AAE-VERY-BAD-SECRET-DO-NOT-DO-THIS"
    - echo "Используем токен $TELEGRAM_TOKEN для запуска..."
    # Эмуляция запуска через compose
    - docker compose up -d
