services:
  hashicorp_vault:
    image: hashicorp/vault:2.0
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - ./vault/secrets:/vault/secrets # для сохранения секретов
      - ./vault/config:/vault/config # для хранения конфига
    #cap_add:
     # - IPC_LOCK # для безопасности (блокировка памяти)
      #- SETFCAP
    #command:
     # server -config=/vault/config/vault_Config.hcl
    entrypoint: ["vault", "server", "-config=/vault/config/vault_Config.hcl"]
