stages:
  - lint
  - security
  - test
  - build
  - cleanup

variables:
  DOCKER_DRIVER: overlay2
  # Ссылки на твои будущие образы в реестре GitLab
  BOT_IMAGE: $CI_REGISTRY_IMAGE/bot:$CI_COMMIT_REF_SLUG
  WEATHER_IMAGE: $CI_REGISTRY_IMAGE/weather:$CI_COMMIT_REF_SLUG

# 1. Этап Линтинга
lint-code:
  stage: lint
  image: python:3.13-slim
  script:
    - pip install flake8
    - flake8 Bot/ weather/ --exclude=venv,migrations

# 2. Этап Безопасности
secret-scan:
  stage: security
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --source .

# 3. Этап Тестирования (с временным Vault)
run-tests:
  stage: test
  image: python:3.13-slim
  services:
    - name: hashicorp/vault:latest
      alias: vault
      command: ["server", "-dev", "-dev-root-token-id=root"]
  variables:
    VAULT_ADDR: "http://vault:8200"
  script:
    - pip install -r Bot/requirements.txt hvac pytest
    - python -m pytest Bot/tests/  # Путь к твоим тестам
  # Это позволяет тестам видеть "сервис" vault по сети GitLab

# 4. Этап Сборки и Пуша в Registry
build-images:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $BOT_IMAGE -f Bot/Dockerfile .
    - docker build -t $WEATHER_IMAGE -f weather/Dockerfile .
    - docker push $BOT_IMAGE
    - docker push $WEATHER_IMAGE
  only:
    - main

# 5. Этап Очистки
clean-up:
  stage: cleanup
  script:
    - echo "Cleaning up temporary build artifacts..."
    - rm -rf .cache/
  when: always
