# bad ci/cd
# import docker image to start dind
# Bad practice 1: latest docker image
image: docker:latest

services:
  - docker:dind

# define stages
# bad practice 2: 1 stage build and deploy
stages:
  - build_and_deploy

# bad practice 3: define secrets in code
variables:
  TELEGRAM_TOKEN: "12345678:ABCDEF"
  WEATHER_API_KEY: "secret-key-123"

# Our code
build_and_deploy:
  stage: build_and_deploy
  tags:	# define tag (no working without it)
    - saas-linux-small-amd64
  script:
    - docker build -t weather-logic ./Lab-4/weather # build docker image
    - docker build -t telegram-bot ./Lab-4/Bot 	# build docker image
    - echo "Deploying . . . "	# print
    - export TELEGRAM_TOKEN="123456789:AAE-VERY-BAD-SECRET-DO-NOT-DO-THIS" 
    - echo "Используем токен $TELEGRAM_TOKEN для запуска..."
    # Эмуляция запуска через compose
    - cd Lab-4
    - docker compose -f Compose.yaml up -d # compose up
# Bad practice 4: No tests

