apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.nginx_app.service.type }}
  selector:
    app: {{ .Values.nginx_app.service.selectApp }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx_app.service.port }}
      targetPort: {{ .Values.nginx_app.service.targetPort }}
      nodePort: {{ .Values.nginx_app.service.nodePort }}
